### ISSUE TITLE
Affiliation seems to require URL

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta-generator#1]
The type of the `affiliation` field for authors in the context is `xsd:string`, but the editor seems to be enforcing that it be a URL. Screenshot:

<img width="362" alt="codemeta-affiliation" src="https://user-images.githubusercontent.com/766407/76259159-e25a0700-6209-11ea-9368-d184566bff41.png">

**Comment by ProgVal** [comment]
Hmm. My understanding is that affiliation should actually be an Organization, according to https://github.com/codemeta/codemeta/blob/master/codemeta.jsonld#L14 + https://schema.org/affiliation

Though I agree most people would want a name there, so let's generate an Organization with a name.

**Comment by mbjones** [comment]
Aha. That's against master, which has a number of pending schema changes that have not yet been released.  I was referencing the 2.0 release schema, which has affiliation as `xsd:string`.  @cboettig , @amoeba, and I have been talking about another release to further align with schema.org, to clean up some ambiguity around authors/creators, and to clarify the correct namespace URI for use.  

For now, I think the generator should generate files that validate against the current release namespace: https://doi.org/10.5063/schema/codemeta-2.0  When we do a new release we can update the generator to output files that match that vocabulary, which as of yet has not been assigned a namespace.

**Comment by ProgVal** [comment]
> For now, I think the generator should generate files that validate against the current release namespace: https://doi.org/10.5063/schema/codemeta-2.0

The only difference I see with the document in master is the addition of `"creator": { "@id": "schema:creator"},`. `affiliation` are unchanged.

Don't you mean https://doi.org/10.5063/schema/codemeta-1.0 ?

**Comment by mbjones** [comment]
@ProgVal you are absolutely right, I had been looking at 1.0.  We should be producing a `schema:Organization` to be compatible with 2.0. Sorry for the confusion.

**Comment by ProgVal** [comment]
Sure, will do. thanks!
