### ISSUE TITLE
Max number of authors

### ISSUE THREAD

**Issue by gahughes** [codemeta/codemeta-generator#13]
Added a large number of authors and contributors 24 and 13. Fails to validate or give an error.

**Comment by gahughes** [comment]
ok I can import 25 of the same author so one of the entires has an error I just do not know which one.

**Comment by progval** [comment]
I don't have the issue. What error do you get, and with what input? Could you provide a screenshot?

**Comment by gahughes** [comment]
I found the problem. For one of the "id" entries I just put "BLANK" as a place holder, with no http...
I added it by hand and when I hit validate I got no error.

**Comment by progval** [comment]
the software's `"id"`? Yeah, it has to be a URL. You can omit it entirely, if you don't have a good value for it, though.
