### ISSUE TITLE
Multi-context codemeta.json doesn't validate

### ISSUE THREAD

**Issue by sdruskat** [codemeta/codemeta-generator#18]
Hi 👋, helpful to have this tool, thanks for providing it!

I have a question about the validation of CodeMeta in general, and the implementation in the generator. As far as I had understood, CodeMeta files are "simply" JSON-LD files, and have no limit on the contexts they can use (otherwise, as far as I understand this would defy the reasoning behind having linked data in the first place).

I tried validating a multi-context codemeta.json file:

```json
{
  "@context": [
    "https://doi.org/10.5063/schema/codemeta-2.0",
    {
      "hermes": "https://software-metadata.pub/ns/hermes/"
    }
  ],
  "@type": "SoftwareSourceCode",
  ...
}
```

This gives me a warning that the context can only be the single CodeMeta context.

I gather that it may be *really* complicated/impossible to validate such a file based on all contexts, perhaps even impossible.
However, perhaps this could be communicated better in the tool, e.g., by stating that the validation works for "pure" CodeMeta files only.

Or have I got it wrong altogether? (That's a distinct possibility, as I don't have too much experience in working with JSON-LD.)

Thanks!

**Comment by progval** [comment]
You're right, it's valid but this tool works on a very restricted subset of JSON-LD; it doesn't even perform compaction/expansion
