### ISSUE TITLE
Switch to jsonld.js to load and dump documents

### ISSUE THREAD

**Issue by progval** [codemeta/codemeta-generator#25]
The current code has some strong restrictions on what it accepts as input, by treating it as "dumb JSON" instead of processing it like a JSON-LD document. Additionally, it means we need to always handle cases of single-value + list.

Instead, we should use jsonld.js to expand documents, then work on the expanded document which has a more regular format.

#24 also introduces some complexity due to needing to make the output vary depending on the codemeta version (`codemeta:continuousIntegration` + `contIntegration` + `codemeta:isSourceCodeOf` in v2 vs `continuousIntegration` + `codemeta:contIntegration` `isSourceCodeOf` in v3), which would be taken care of by simply using jsonld.js to compact with the right version's context before printing the document.

**Comment by progval** [comment]
Another option (though not necessarily exclusive) is to use rdfjs to query triples. It should make handling of roles easier, at the cost of increased overall complexity. I don't know if it's worth it.

**Comment by hjonin** [comment]
On it
