### ISSUE TITLE
Validator rejects output generated by codemetapy

### ISSUE THREAD

**Issue by apirogov** [codemeta/codemeta-generator#35]
The validator seems to only accept a single hard-coded `@context` with codemeta, but [codemetapy](https://github.com/proycon/codemetapy) generates a file with context given as a list:

```
"@context": [
        "https://doi.org/10.5063/schema/codemeta-2.0",
        "https://w3id.org/software-iodata",
        "https://raw.githubusercontent.com/jantman/repostatus.org/master/badges/latest/ontology.jsonld",
        "https://schema.org",
        "https://w3id.org/software-types"
    ],
```

This is valid JSON-LD, but [this validator](https://codemeta.github.io/codemeta-generator/) rejects it.
I understand that implementing the validation fully respecting arbitrary RDF contexts might be difficult for different reasons. But a possible solution could be:

1. If there is more than one context, check that codemeta context URL is part of the list
2. for unknown fields, if there are other contexts beyond codemeta, make a **warning** instead of an error (because it might be valid for the other contexts)

**Comment by progval** [comment]
It's a known limitation that this is a generator and not primarily a validator, so it rejects plenty of valid documents. However, for this particular case, #32 should fix it.
