### ISSUE TITLE
Use blank node identifiers to merge author nodes

### ISSUE THREAD

**Issue by progval** [codemeta/codemeta-generator#42]
Since #34 we export every author as two different JSON objects.

When an URI is not set of that author, we should use [blank node identifiers](https://www.w3.org/TR/json-ld11/#identifying-blank-nodes) in order to identify identical nodes. Otherwise, per JSON-LD semantics, they should be considered different nodes.

cc @hjonin

**Comment by hjonin** [comment]
Does it mean that we should generate this kind of codemeta when the URI is not set?
```
{
    "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
    "type": "SoftwareSourceCode",
    "author": [
        {
            "id": "_:author_1",
            "type": "Person",
            "givenName": "jane"
        },
        {
            "type": "schema:Role",
            "schema:author": {
                "id": "_:author_1",
                "type": "Person",
                "givenName": "jane"
            },
            "schema:roleName": "dev"
        }
    ],
    "name": "test"
}
```

And that the function https://github.com/codemeta/codemeta-generator/blob/9bf79ad784a0e7b99be3c7ced5f7b6f8d8e7ace3/js/codemeta_generation.js#L323 should test equality for ids and then fallback to name and email ?

**Comment by progval** [comment]
Yes, exactly. Or maybe this:

```json
{
    "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
    "type": "SoftwareSourceCode",
    "author": [
        {
            "id": "_:author_1",
            "type": "Person",
            "givenName": "jane"
        },
        {
            "type": "schema:Role",
            "schema:author": "_:author_1",
            "schema:roleName": "dev"
        }
    ],
    "name": "test"
}
```
