### ISSUE TITLE
Cannot add a role to a contributor

### ISSUE THREAD

**Issue by progval** [codemeta/codemeta-generator#53]
When adding a role to a contributor (not an author), I get the error `Unknown field "contributor" in "contributor".`

cc @hjonin

**Comment by hjonin** [comment]
It is linked to the [latest modification](https://github.com/codemeta/codemeta-generator/pull/52); we have to [add a `contributor` property to the `roleFieldValidators`](https://github.com/codemeta/codemeta-generator/blob/f060ff077e3ba5fb43eacd4d75dbc85b65b64a3c/js/validation/things.js#L310). However, it means that it does not check if the role is associated to an author (in which case it should be `schema:author` to be validated) or a contributor (then `contributor`). Is it still OK with you?

**Comment by progval** [comment]
good catch, thanks.

we should check the properties match eventually, but for now let's only change it so it passes. Could you do it?

**Comment by megasanjay** [comment]
Adding a reply to this. Should the correct syntax be the following in this instance?
```json
 "author": [
        {
            "id": "_:author_1",
            "type": "Person",
            "givenName": "test"
        },
        {
            "type": "schema:Role",
            "schema:author": "_:author_1",
            "schema:roleName": "test",
            "schema:startDate": "2024-08-15"
        }
    ],
    "contributor": [
        {
            "id": "_:contributor_1",
            "type": "Person",
            "givenName": "Test 2"
        },
        {
            "type": "schema:Role",
            "schema:contributor": "_:contributor_1",
            "schema:roleName": "Test3"
        }
    ]
```

**Comment by progval** [comment]
`contributor` instead of `schema:contributor`, but that's correct too

**Comment by megasanjay** [comment]
@progval so both are valid?

``` json
 "contributor": [
        {
            "id": "_:contributor_1",
            "type": "Person",
            "givenName": "Test 2"
        },
        {
            "type": "schema:Role",
            "schema:contributor": "_:contributor_1",
            "schema:roleName": "Test3"
        }
    ],

 "contributor": [
        {
            "id": "_:contributor_1",
            "type": "Person",
            "givenName": "Test 2"
        },
        {
            "type": "schema:Role",
            "contributor": "_:contributor_1",
            "schema:roleName": "Test3"
        }
    ]
```

**Comment by progval** [comment]
yes, both are semantically equivalent

**Comment by megasanjay** [comment]
> yes, both are semantically equivalent

Gotcha. It's just that the validator was failing on them. I guess we shall need to wait for an update to the generator
